name: Ruff Lint Check

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'  

jobs:
  lint:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff Linter
      run: |
        mkdir -p lint-reports
        ruff . --format=stylish > lint-reports/ruff-report.txt
      continue-on-error: true  

    - name: Upload Lint Report
      uses: actions/upload-artifact@v3
      with:
        name: ruff-lint-report
        path: lint-reports/ruff-report.txt
